[package]
name = "closestAirport"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9"}
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.133"
